ARG PHP_VERSION=8.5

FROM mlocati/php-extension-installer AS php-extension-installer
FROM composer:2 AS composer_bin

FROM php:${PHP_VERSION}-fpm-alpine AS php-fpm-dev




RUN set -xe \
  && apk add --no-cache zip unzip acl git ca-certificates wget curl bash tzdata

WORKDIR /var/www

COPY --from=php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions intl zip opcache pdo_mysql xdebug

COPY --from=composer_bin /usr/bin/composer /usr/local/bin/composer

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

COPY docker/dev/php/zzz-custom.ini "$PHP_INI_DIR/conf.d/"
# (si tu n’as pas les .ini en glob, laisse tes COPY un par un)

EXPOSE 9000

