services:

  mysql-dev:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/database/schema/schema-create.sql:/docker-entrypoint-initdb.d/schema-create.sql
      - training-pulse-mysql-dev:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    working_dir: /var/www
    volumes:
      - ./api:/var/www:delegated
      - training-pulse_composer_cache_dev:/tmp/composer
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql-dev:3306/${MYSQL_DATABASE}?serverVersion=${MYSQL_VERSION}
      COMPOSER_HOME: /tmp/composer
      XDEBUG_MODE: ${XDEBUG_MODE:-off}

      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      STRAVA_REDIRECT_URI: ${STRAVA_REDIRECT_URI}

      JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
      JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
      JWT_PASSPHRASE: '${JWT_PASSPHRASE:?JWT_PASSPHRASE is required}'

    user: "${UID:-1000}:${GID:-1000}"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/var/www
      - ./docker/dev/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/dev/nginx/certs:/etc/nginx/certs:ro

volumes:
  training-pulse_composer_cache_dev:
  training-pulse-mysql-dev: