api_platform:
    title: Training Pulse API
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
    docs_formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_items_per_page: 30
        pagination_client_items_per_page: true
        pagination_items_per_page_parameter_name: itemsPerPage
when@dev:
    api_platform:
        defaults:
            stateless: false
