; Timezone
date.timezone=Europe/Zurich

; Uploads
upload_max_filesize=50M
post_max_size=60M

; Logs dans docker
log_errors=1
error_log=/proc/self/fd/2

; Symfony dev: reload immédiat
opcache.revalidate_freq=0

; Xdebug piloté par env (compose: XDEBUG_MODE=off par défaut)
xdebug.mode=${XDEBUG_MODE}
xdebug.start_with_request=trigger
xdebug.discover_client_host=1


opcache.enable_cli=0